### ISSUE TITLE
Proposal (Core and Essentials command reorganization)

### ISSUE THREAD

**Issue by tonibm19** [mc-server/Essentials#23]
This is just an idea I have, I want to know your opinion.

Core was originally planned to hold vanilla commands, but it got bigger and bigger.
Now Essentials in inside mc-server my proposal is to move non-vanilla commands from Core to Essentials.

What do you think?

**Comment by NiLSPACE** [comment]
Makes sense to me. ^^

**Comment by tonibm19** [comment]
@madmaxoft 
@bearbin 
@tigerw 
?

**Comment by tigerw** [comment]
I am in agreement.

Furthermore, all Vanilla core commands should be coded directly into the server.

**Comment by NiLSPACE** [comment]
I don't agree with that though. I think MCServer should have no command by default (except for some in the console).

**Comment by tigerw** [comment]
But why?

**Comment by bearbin** [comment]
I don't think it's necessary to move the commands into the server itself, it's easier to maintain a Plugin and it's enabled by default.

I do agree with reorganising the commands between Core and Essentials to put vanilla commands in core and others in essentials.

(Splitting essentials into different plugins might be nice, but It's not needed ATM).

**Comment by tonibm19** [comment]
Then, if anyone disagrees, I think I'll move from Core to here all commands that are on bukkit to essentials.
(Ej /fly, /tpa...)
The problem is that the contributors and commits from that commands to core will get removed here, anyway to avoid this?

**Comment by madmaxoft** [comment]
I agree with the move.

Technically, the contributors will be preserved in git history of the Core plugin; the only thing we'll be losing is the "blame" capability. I think I can live with that.

**Comment by tonibm19** [comment]
One question, what do you prefeare, moving here all Essentials commands(some are in vanilla too) which are in Core and remove from there or to keep Essentials-vanilla commands in core?

**Comment by madmaxoft** [comment]
Can you give an example of such a command? Why would it be in both? Is the Essentials version somewhat better?

I think you should move the commands in batches, a few at a time, and submit a PR to Essentials that implements those commands, while at the same time having a PR in Core removing those commands, so that it's easier to update both at the same time.

**Comment by tonibm19** [comment]
see http://wiki.ess3.net/wiki/Command_Reference
One example is gamemode.
I prefer to keep them on core

**Comment by tonibm19** [comment]
See https://github.com/mc-server/Core/issues/143

**Comment by madmaxoft** [comment]
If it's in vanilla and the Essentials has nothing to add to that command funcionality-wise, then keep it in the Core, definitely.
