### ISSUE TITLE
Mute doesn't work

### ISSUE THREAD

**Issue by mathias-github** [mc-server/Essentials#47]
When using the /mute command or jailing players, they can still chat.

**Comment by tonibm19** [comment]
I tried and it worked with latest version.
Let me know if it's still not working

**Comment by mathias-github** [comment]
Still not working on my server :(

**Comment by tonibm19** [comment]
Try putting Essentials before Chatter.

**Comment by mathias-github** [comment]
Yep, completely forgot about that. Thanks!

Is there any better way to change the order than renaming plugins? They always seem to start in alphabetical order, no matter how they are arranged in the settings.ini file.

**Comment by tonibm19** [comment]
What? I thought it was about their order in the .ini
Then ask someone other
